name: Deploy to dev.to

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install `dev-to-git`
        run: npm i -g dev-to-git

      - name: Deploy to dev.to
        run: dev-to-git
        env:
          DEV_TO_GIT_TOKEN: ${{ secrets.DEVTO_TOKEN }}
