name: Deploy to dev.to

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to dev.to
        run: npx dev-to-git --repository-url https://github.com/ken-matsui/devto-content.git
        env:
          DEV_TO_GIT_TOKEN: ${{ secrets.DEVTO_TOKEN }}
